Encode bytea fields
uyuni-project/inter-server-sync pull request #72
Opened 2024-04-08 21:20 UTC by rjpmestre

Aims to fix https://github.com/SUSE/spacewalk/issues/23726

We detected a case where binary data contained backslashes. We've been using pq.QuoteLiteral but in these cases it we end up getting invalid insert statements.
Besides, it also had some line breaks and some sensitive information.

My suggestion here is to encode this type of data to hexadecimal as it would address the problems with escaping characters, keeps the statements tighter and also masks any sensitive information that may be copied around servers.

We apply the same escape method to varchar fields. However i wanted to exclude them, at least for now. Encoding and decoding means having an additional processing overhead and this hasn't been a problem so far.

2024-04-11 10:30 UTC, rjmateus approved these changes
lgtm

2024-05-20 09:37 UTC, aaannz requested changes
Changelog entry is needed

2024-05-20 20:06 UTC, aaannz requested changes

2024-05-20 20:06 UTC, aaannz commented on inter-server-sync.changes.rjmestre.dumper_encode_bytea_fields
> +- Encode bytea fields
```suggestion
- Encode bytea fields (bsc#1219965)
```

2024-05-21 09:39 UTC, aaannz approved these changes
Thanks!

2024-05-21 09:40 UTC, merged